name: flutter_application_1
description: A new Flutter project.

environment:
  sdk: '>=3.4.0 <4.0.0'

version: 1.0.0+1  # Add this line

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  collection: any  # Optional: specify a compatible version if needed
  curved_navigation_bar: ^1.0.6  # Latest version
  sqflite: ^2.0.3  # Ensure this is the latest version
  path: ^1.8.3     # Add this if not already present

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true  






  